apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aggregate-1
spec:
  schedule: "55 23 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aggregate-1
        spec:
          containers:
          - name: aggregate-1
            image: batteryho/aggregate:v0.2
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8300
          restartPolicy: Never